"""empty message

Revision ID: 15fe09731331
Revises: 
Create Date: 2021-08-18 23:36:59.634459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15fe09731331'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('friend_id', sa.Integer(), nullable=False))
    op.drop_constraint('friends_friend_id_fk_fkey', 'friends', type_='foreignkey')
    op.create_foreign_key(None, 'friends', 'users', ['friend_id'], ['user_id'])
    op.drop_column('friends', 'friend_id_fk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('friend_id_fk', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.create_foreign_key('friends_friend_id_fk_fkey', 'friends', 'users', ['friend_id_fk'], ['user_id'])
    op.drop_column('friends', 'friend_id')
    # ### end Alembic commands ###
